### ISSUE TITLE
Having trouble installing in OpenSuse Tumbleweed (KDE)

### ISSUE THREAD

**Issue by maxmoritz** [seebk/LaTeXText#12]
Hi,

I can't get this extension to work in Tumbleweed, probably due to a missing package. But the naming scheme is quite different so I have no clue which package to install.
I have run the install.sh, my extension folder contains latextext_gtk3.inx, latextext_gtk3.py, latextext.py and latextext.pyc.
The extension appears in Inkscape but when I try to run it, a small windows opens and closes immediately afterwards. 

I have installed the latest texlive distrubtion. Also I'm sure to have installed pdf2svg, python and python2-lxml and a whole bunch of other "python" and python3 packages. python-gi I'm not sure about, I can't find it in my package manager.

Thanks for your help.

/EDIT

I miraculously found the package in OpenSuse, it's called **python2-gobject-Gdk**.

It seems to be working now, however I get this warning upon running the rendering process, are these troublesome?:

(latextext_gtk3.py:16918): Gtk-WARNING **: 22:41:12.317: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(latextext_gtk3.py:16918): Gtk-WARNING **: 22:41:12.317: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(latextext_gtk3.py:16918): Gtk-WARNING **: 22:41:12.317: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

**Comment by seebk** [comment]
Thanks, I will add a note to the readme with the proper package names on 
other Linux distributions.

The warnings should be no problem as far as the UI works fine.

**Comment by g7fernandes** [comment]
I'm receiving similar messages from Inkscape 0.92 on OpenSUSE Tumbleweed and it is not generating anything. 

GLib-GIO-Message: 11:25:11.372: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(latextext_gtk3.py:7961): Gtk-WARNING **: 11:25:11.379: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(latextext_gtk3.py:7961): Gtk-WARNING **: 11:25:11.379: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(latextext_gtk3.py:7961): Gtk-WARNING **: 11:25:11.380: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "latextext_gtk3.py", line 158, in on_btnApply_clicked
    self.run_callback()
  File "/home/gabriel/.config/inkscape/extensions/latextext.py", line 476, in run
    rendergroup = self.align_placement(rendergroup, txt)
  File "/home/gabriel/.config/inkscape/extensions/latextext.py", line 346, in align_placement
    (tx, ty) = t.get_translation()
  File "/home/gabriel/.config/inkscape/extensions/latextext.py", line 196, in get_translation
    return (self.matrix[0][2], self.matrix[1][2])
IndexError: list index out of range
Traceback (most recent call last):
  File "latextext_gtk3.py", line 177, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.output()
  File "/usr/share/inkscape/extensions/inkex.py", line 270, in output
    self.document.write(sys.stdout)
  File "src/lxml/etree.pyx", line 2039, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 733, in lxml.etree._tofilelike
  File "src/lxml/etree.pyx", line 316, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/serializer.pxi", line 650, in lxml.etree._FilelikeWriter.write
TypeError: write() argument must be str, not bytes
