### ISSUE TITLE
pdfTex cannot process preamble

### ISSUE THREAD

**Issue by hktwo** [seebk/LaTeXText#14]
Hello,

I am using Inkscape 0.92 on Windows 7.

I get the following log message when trying to run Text with LaTeX (GTK3) on the preamble file mathpreamble_sans.tex

---EDIT---
Cutting some of the log message.

> 
Command "pdflatex c:\users\hyunmoon\appdata\local\temp\tmpl6zpvd\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

 This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit)

entering extended mode

(c:/Users/Hyunmoon/AppData/Local/Temp/tmpl6zpvd/tmp.tex

LaTeX2e <2017-04-15>

Babel <3.18> and hyphenation patterns for 75 language(s) loaded.

Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/Hyunmoon/AppData/Local/MiKTeX/2.9/miktex/log/pdflatex.log

You may want to visit the MiKTeX project page, if you need help.

Traceback (most recent call last):
  File "latextext_gtk3.py", line 150, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 465, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.fontsize, self.options.scale)
  File "latextext.py", line 569, in render
    raise RuntimeError()
RuntimeError

**Comment by csorvagep** [comment]
It seems like your error is related to the latex file, or the latex code you placed on the svg. You can check the log file for the error messages, or just try to compile the tex file outside of inkscape. The file should be in location `c:/Users/Hyunmoon/AppData/Local/Temp/tmpl6zpvd/tmp.tex`.

**Comment by hktwo** [comment]
Thanks! It turned out I had a few packages missing from MiKTeX. It works now :)
