### ISSUE TITLE
Running the extension does not render

### ISSUE THREAD

**Issue by FelixBurkhard** [seebk/LaTeXText#17]
When I try to run the extension the text is not rendered, but the new 'Rendered Latex' Layer is created. It does not matter if I use 'Text with LaTeX (GTK3)' or 'Text with LaTeX'.

My Installation:

- Windows 10  - 64 bit
- Inkscape 0.92.3
- LaTexText 0.1.1
- MiKTeX 2.9.6642

What I did:

- create new document
- create textobject with $\alpha$
- create new layer called 'Latex'
- move text to layer
- run extension with default options

Since there is no error message I am not sure if there is a bug or if I just set something up the wrong way.  If you need any more information just let me know.

**Comment by csorvagep** [comment]
How did you created the textobject? If you select an area as a textbox (click and drag) the Inkscape creates a different object which is not detectable by the addon. You should use a simple text by only clicking on the sheet and type the text. Related issue: #5

**Comment by FelixBurkhard** [comment]
Thanks a lot! Problem solved...
