### ISSUE TITLE
Windows rendering issue

### ISSUE THREAD

**Issue by aaronmross** [seebk/LaTeXText#19]
Thanks for building this package, excited to get it working.

I am having an issue when I attempt to render the LaTeX layer:

![image](https://user-images.githubusercontent.com/34897821/46296830-41254680-c569-11e8-814c-b8eaec72a774.png)

Additionally, trying to use the other rendering option (Text with Latex) gives me a different error:
"Traceback (most recent call last):
  File "latextext.py", line 13, in <module>
    from lxml import etree
ImportError: No module named lxml"

My MikTeX package and Inkscape are all up to date.

**Comment by seebk** [comment]
Did you use the extension installer exe or copied the files manually? It 
seems some Python modules in the Inkscape Python folder are not found.

**Comment by aaronmross** [comment]
I used the extension installer.

**Comment by seebk** [comment]
That's weird. At the moment I do not have a Windows machine to check if the installer still works with Inkscape 0.9.23. Do you have a non-standard directory setup, e.g. Inkscape is the portable version or installed outside of `C:\Program Files\`? Is it maybe a 32bit version of Inkscape?

**Comment by seebk** [comment]
Finally, I got a windows machine to test with latest Inkscape. Still works for me.

**Comment by aaronmross** [comment]
I needed to reinstall my python package, works now. Thanks!

**Comment by seebk** [comment]
Great :)
