### ISSUE TITLE
Preamble in Windows version crashes

### ISSUE THREAD

**Issue by thatlittleboy** [seebk/LaTeXText#2]
Thanks for taking your time to work on this extension. I am on Windows 10, 64 bit running Inkscape 0.92.2.

In the LaTexText(GTK3) window, I can't seem to open the window/dialog to search for Preamble file directory, as it crashes instantly after clicking it.

![test](https://user-images.githubusercontent.com/30731072/32721040-3073dc00-c8a0-11e7-8697-89b13f68c22c.gif)

**Comment by seebk** [comment]
Oh yes, I think there were some important files missing in the final windows installer package. This should be fixed now with the latest 0.1.1 release. https://github.com/seebk/LaTeXText/releases/tag/v0.1.1

 Please check and report back if this solves your your problem

**Comment by thatlittleboy** [comment]
Yes, it works nicely now. Thanks!

There's another minor issue which I forgot to mention previously. During installation of LatexText (either as a fresh installation or as an update from 0.1.0 to 0.1.1) for Windows, the default folder would always be `./Inkscape/New Folder`. 

Installation of the files into this folder won't work (the installation completes, but Inkscape does not recognize the extension), and I would have to copy the contents from `New Folder` back to the parent `Inkscape` directory, before the extension would work. It would be nice if you could fix this as well.

**Comment by seebk** [comment]
That's strange.... What is the full path proposed by the installer on your computer?

For me it is always "C:\Program Files\Inkscape".

**Comment by thatlittleboy** [comment]
I am installing to "D:\Program Files\Inkscape", but when I choose Inkscape from the dialog, the installer always suggests "D:\Program Files\Inkscape\New Folder". I will try to replicate this on my desktop (running Windows 10 as well) over the weekend and report back, hopefully with a .gif of the issue. Thanks for the efforts so far!

**Comment by thatlittleboy** [comment]
I am facing the same problem on my desktop (windows 10, 64 bit, Inkscape 0.92.2). I am doing a fresh installation of Inkscape and LatexText.

As you can see from the picture, the Inkscape folder is clearly selected, but a `New Folder` is appended onto the end. This happens for any folder I choose, not just the Inkscape one.

![rect6077](https://user-images.githubusercontent.com/30731072/32947773-a81829ac-cbd7-11e7-95cd-5490b11239a0.png)

 If I then click 'Ok' with the Inkscape folder selected, I get this, as expected (but this is wrong, since it would be installed into the wrong folder).

![latextext-0 1 1_win64 tmp_2017-11-17_20-43-55](https://user-images.githubusercontent.com/30731072/32947867-09d1f93e-cbd8-11e7-9a59-480df72593dd.png)

**Comment by seebk** [comment]
Ok, think I have an idea where this "New Folder" is coming from. I will try to fix it soon.

**Comment by isabelcpv** [comment]
> 
> 
> Oh yes, I think there were some important files missing in the final windows installer package. This should be fixed now with the latest 0.1.1 release. https://github.com/seebk/LaTeXText/releases/tag/v0.1.1
> 
> Please check and report back if this solves your your problem

I have  a similar problem: On Extensions/ Render when I hit "Text with Latex (GTK3)" I can't seem to open the window/dialog, as it crashes instantly after clicking it.

I'm running Inkscape 0.92.3 over Win10, 64bit but I'm already using the [latest release](https://github.com/seebk/LaTeXText/releases) of LatexTex..

**Comment by seebk** [comment]
Any error messages you get when the windows closes or after is is closed?

**Comment by seebk** [comment]
> As you can see from the picture, the Inkscape folder is clearly selected, but a `New Folder` is appended onto the end. This happens for any folder I choose, not just the Inkscape one.
> 

The "New Folder" does not appear anymore when I build an installer with the latest Git head. So I will close this.
