### ISSUE TITLE
Error while using \text command inside math mode

### ISSUE THREAD

**Issue by sondretordal** [seebk/LaTeXText#4]
Hi,

I get the following error message when I try to use the \text command inside math mode. The extension works otherwise:

Message:
Command "pdflatex c:\users\motion~1\appdata\local\temp\tmplpg5_z\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

Also Inkscape crashes when I use "Text with Latex (GTK3)" instead of using "Text with Latex " only.

I am using Windows 10 and Inkscape 0.92.2 togeher with MikTex.

**Comment by seebk** [comment]
I think you have to load the amsmath package in the Latex preamble to use \text{}.

**Comment by sondretordal** [comment]
Ok, I understand. But where do I put the preamble file? I tried to put in the same solder as the *.svg file, also I tried the root folder of the "latextext.py" file location. Both times it crashes and the error message says it cant find the "mathpremable.tex" file.

Any suggestions?

**Comment by seebk** [comment]
Sorry, took a few weeks to answer... You have to give the full path to the preamble file (you can select it by clicking on the "..." button).

To make things easier I have just added an additional parameter field in the UI where one an add a list of additional packages to be loaded. `amsmath` and `amssymb` are the default. You can use the current masster branch version of the extension to give it a try.

**Comment by HolyMoleyGit** [comment]
Thanks for building this!  I was having issues with the \text{} functino as well.  I couldn't get the preamble to work on the windows install, nor could I see the "additional packages" field.  I downloaded the Linux install files and put the .inx and .py files into the Inkscape extensions folder and now I can see the additional packages field and it works perfectly, just seems like the windows installer file needs updating.

Thanks again!

**Comment by seebk** [comment]
Yes, it will be in the installer with the next release.
