### ISSUE TITLE
TexText is still alive

### ISSUE THREAD

**Issue by jcwinkler** [seebk/LaTeXText#6]
Hello,

I would like to comment that the Inkscape extension TexText is still alive and actively developed:

[https://bitbucket.org/pitgarbe/textext](https://bitbucket.org/pitgarbe/textext)

It would be nice if this can be noted in the readme. Since the approaches and goals (editing of one node in TexText and a bunch of nodes in LaTeXText) are different to some extend we do not competete.

Currently the 0.7 release is pending as a pull request (see [https://bitbucket.org/jcwinkler/textext](https://bitbucket.org/jcwinkler/textext) for a preview).

Anyway, maybe we can bundle our efforts? We are still using pstoedit and need to move to pdf2svg or even better command line Inkscape. I am just figuring out how to achive this  _seamlessly_.

There is also the extension [WriteText](https://github.com/wanglongqi/WriteTeX) which is quite similar to TexText.

Thank you and regards.

**Comment by seebk** [comment]
I wasn't aware of your fork of TexText. Maybe you should contact the original author to remove the note that textext is not developed any further from the website https://pav.iki.fi/software/textext/. This is what you first find on google when looking for TexText and it is not clear which of the many forks are active and stable.

I will remove the note that TexText is abandonend from my README and just state that I once forked from Pauli Virtanen.

**Comment by jcwinkler** [comment]
Thanks. We already tried to contact Pauli, the original other, via several communication channels. However, we did not get ever a reply...
