### ISSUE TITLE
Use without admin rights

### ISSUE THREAD

**Issue by spsamare** [seebk/LaTeXText#7]
I am working on a PC without admin rights. Therefore, I have to limit the use to portable version of Inkscape  (at least zipped version). Now the issue is how to install this extension manually without admin rights. I tried to extract individual files yet there is an issue:
"Traceback (most recent call last):
  File "latextext_gtk3.py", line 6, in <module>
    import gi
ImportError: No module named gi"
Is there any possibility to overcome this issue without admin rights?

**Comment by seebk** [comment]
I think you can select the portable Inkscape Installation folder during the LaTeXText setup. Have you tried this?

**Comment by seebk** [comment]
No more feedback from the reporter, will close this now.

**Comment by thihakyawjob** [comment]
How to do it?
I am still facing the same problem.
  File "latextext_gtk3.py", line 6, in <module>
    import gi
ImportError: No module named gi
