### ISSUE TITLE
When I use LatexText,a bug.

### ISSUE THREAD

**Issue by LingjieLi** [seebk/LaTeXText#8]
![image](https://user-images.githubusercontent.com/11186255/37653146-cf647a36-2c78-11e8-9532-744a9d7034e0.png)
I don't know why

**Comment by seebk** [comment]
I don't know either :) An empty error message is a bit troubling to debug. When exactly did the message appear? Does it appear with any kind of Inkscape file?

**Comment by LingjieLi** [comment]
When I use WriteTex and LaTexText plugin， I followed the way on official website ,this window appears., I can't get rendered text  . I wander If there is a bug .

**Comment by seebk** [comment]
I think the error message above the white box is a generic one from Inkscape telling there was problem with the extension? The extension error message should be shown in the white box but without an error or feedback it is quite difficult to guess what the problem is. Sorry...

**Comment by LingjieLi** [comment]
Ok thank you for your response
