### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by CarImp64** [seebk/LaTeXText#9]
Hi, I'm Carlo from Italy. I'm a teacher.
I try to execute the LaTexText addon but Inkscape's dialog window reports an error:
Command "pdflatex c:\users\carlo\appdata\local\temp\tmpz5j9o5\tmp.tex -interaction=nonstopmode -halt-on-error" > failed: [Error 2] Impossibile trovare il file specificato

Traceback (most recent call last):
  File "latextext_gtk3.py", line 150, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 465, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.fontsize, self.options.scale)
  File "latextext.py", line 569, in render
    raise RuntimeError()
RuntimeError

**Impossibile trovare il file specificato** -> **The specified file could not be found**

I use Inkscape 0.9.3 and I've installed LaTexText with LaTexText-0.1.1_win64.exe file
My o.s. is win10 64bit. The 4 files are located correctly (C:\Program Files\Inkscape\share\extensions).
Do you have any suggestions for me?

**Comment by seebk** [comment]
It looks like it does not find the `pdflatex` command. Have you installed Miktex?

**Comment by CarImp64** [comment]
Miktex? No. I'll install it soon and try again. Thank you!!

**Comment by CarImp64** [comment]
I thought that miktex was included in the installation file. Sorry. I'll try soon.

**Comment by CarImp64** [comment]
Hi. I've installed miktek basic. I try to render two expression

$v_{e(t)} =L_{e}\frac{di_{e(t)} }{dt} +R_{e} i_{e(t)}$
and
$\alfa + \beta +\gamma = 180^\circ$

the first is correct rendering, the second generate an error this is the log:

Using a previous render layer...
2 text nodes were found.
ID: text817
$v_{e(t)} =L_{e}\frac{di_{e(t)} }{dt} +R_{e} i_{e(t)}$

[1.0, 0.0, 0.0, -1.0, 401.475, 412.472]
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
matrix(0.352778,0.000000,0.000000,0.352778,47.625000,95.160713)
ID: text833
$\alfa +\beta +\gamma = 180^\circ$


Command "pdflatex c:\users\carlo\appdata\local\temp\tmp08fazx\tmp.tex -interaction=nonstopmode -halt-on-error" failed (code 1): 

 This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6630 64-bit)

entering extended mode

(c:/Users/Carlo/AppData/Local/Temp/tmp08fazx/tmp.tex

LaTeX2e <2017-04-15>

Babel <3.18> and hyphenation patterns for 75 language(s) loaded.

("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"

Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

("C:\Program Files\MiKTeX 2.9\tex\latex\base\size10.clo"))

("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"

("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")

("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")

("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.cfg"))

No file tmp.aux.

*geometry* driver: auto-detecting

*geometry* detected driver: pdftex

! Undefined control sequence.

<recently read> \alfa 

                      

l.11     $\alfa

                +\beta +\gamma = 180^\circ$

!  ==> Fatal error occurred, no output PDF file produced!

Transcript written on tmp.log.



Traceback (most recent call last):
  File "latextext_gtk3.py", line 150, in on_btnApply_clicked
    self.run_callback()
  File "latextext.py", line 465, in run
    rendergroup = lat2svg.render(latex_string, self.options.preamble, self.options.fontsize, self.options.scale)
  File "latextext.py", line 569, in render
    raise RuntimeError()
RuntimeError

but if I use \delta instead of \alfa the rendering is perfec. 

Creating a new render layer...
2 text nodes were found.
ID: text817
$v_{e(t)} =L_{e}\frac{di_{e(t)} }{dt} +R_{e} i_{e(t)}$

[1.0, 0.0, 0.0, -1.0, 401.475, 412.472]
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]
matrix(0.352778,0.000000,0.000000,0.352778,47.625000,95.160713)
ID: text833
$\delta +\beta +\gamma = 180^\circ$

matrix(0.352778,0.000000,0.000000,0.352778,43.278275,128.422620)
I think everything works very well! Thanks for your help!

**Comment by seebk** [comment]
On 31.03.2018 13:13, CarImp64 wrote:
> Hi. I've installed miktek basic. I try to render two expression
> 
> $v_{e(t)} =L_{e}\frac{di_{e(t)} }{dt} +R_{e} i_{e(t)}$
> and
> $\alfa + \beta +\gamma = 180^\circ$
> 

I think you want to use \alpha ;)

**Comment by CarImp64** [comment]
GULP!
